on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Version
        run: echo ${{ github.ref_name }} > bin/version.txt
        if: github.ref_type == 'tag'
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Build
        run: go build -o ./bin/ -v ./...
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'bin/nof'
